nlp_engine_name: spacy
models:
  -
    lang_code: en
    model_name: en_core_web_lg
  -
    lang_code: it
    model_name: it_core_news_lg
ner_model_configuration:
model_to_presidio_entity_mapping:
  PER: PERSON
  PERSON: PERSON
  LOC: LOCATION
  LOCATION: LOCATION
  GPE: LOCATION
  ORG: ORGANIZATION
  DATE: DATE_TIME
  TIME: DATE_TIME
  NORP: NRP